'use client';

import {
  THINKING_SPRITE_DEFAULT_FPS,
  THINKING_SPRITE_FRAME_COUNT,
  THINKING_SPRITE_VIEWBOX,
} from '@/lib/generated-thinking-sprite';

const [, , THINKING_VIEWBOX_WIDTH, THINKING_VIEWBOX_HEIGHT_RAW] =
  THINKING_SPRITE_VIEWBOX.split(' ').map(Number);

export const THINKING_FRAME_COUNT = THINKING_SPRITE_FRAME_COUNT;
export const THINKING_DEFAULT_FPS = THINKING_SPRITE_DEFAULT_FPS;
export const THINKING_VIEWBOX_SIZE = THINKING_VIEWBOX_WIDTH;
export const THINKING_VIEWBOX_HEIGHT = THINKING_VIEWBOX_HEIGHT_RAW;
